(setf *default-fill-column* 110)
(setf *default-sound-player* nil)
(setf *default-nick* (format nil "wbooze"))
(setf *default-realname* (format nil "homie"))
(setf *default-web-browser* "/usr/bin/firefox")
(setf *auto-connect-list* '("irc.freenode.net"))
(setf *auto-identify-list* '("irc.freenode.net"))
(setf *nickserv-password-alist* '(("irc.freenode.net" . "password")))

(setf *auto-join-alist* '(("irc.freeenode.net" . ("#maxima" "#lisp" "#clnoobs" "#sbcl" "#lispgames" "#scheme" "#emacs" "#algorithms" "##cs" "##programming" "##math" "##asm" "##linux" "##kernel" "##slackware" "#freenode"))))
